INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1001,'kfozla','Get AWS Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1002,'kfozla','Get AZURE Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1003,'kfozla','Get GCP Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1004,'kfozla','Learn DEVOPS',CURRENT_DATE(),false);